### ISSUE TITLE
Single-character wrapped lines with long options

### ISSUE THREAD

**Issue by OddBloke** [mitsuhiko/click#231]
When I run the script at the bottom I get the following output. I would, obviously, expect ALSOLONG to be all together on the second row.

```
Usage: example.py relatively_long example [OPTIONS] FIRST SECOND LONGISH
                                          A
                                          L
                                          S
                                          O
                                          L
                                          O
                                          N
                                          G

Error: Missing argument "first".
```

--

```py
import click


@click.group()
def foo():
    pass


@foo.group()
def relatively_long():
    pass


@relatively_long.command()
@click.argument('first')
@click.argument('second')
@click.argument('longish')
@click.argument('alsolong')
def example():
    pass


foo()
```

**Comment by JTFouquier** [comment]
Hello.  I was just wondering if there is any progress on this bug?  My options are wrapping very far.
 
T
h
a
n
k
s
!

:)

**Comment by sjagoe** [comment]
I have an open PR for this. I might pull that out into some code that can be applied in projects *using* click if the PR doesn't get reviewed.

**Comment by sjagoe** [comment]
@untitaker Are you able to look at #240?

**Comment by untitaker** [comment]
I don't think it's the correct solution. I'm at a loss why Click wants to indent all options to match up with the command name... generally this is not going to fly on smaller terminals.

**Comment by sjagoe** [comment]
so you would suggest just wrapping to the next line, maybe with a small indent (4-8 spaces)?

**Comment by JTFouquier** [comment]
Does anyone have a suggestion for how to get around this issue in the most efficient way possible?  I used Python 2.7, but if I switch to 3.0 will that fix it?  Or anything less time intensive?  Thank you for any pointers!

**Comment by untitaker** [comment]
I haven't looked into the issue properly. #240 is a workaround, but a proper fix is needed.

**Comment by JTFouquier** [comment]
Okay, I see #240 changes formatting.py but i figured this was something that needed to be done in Click and then I'd reinstall Click.  Is this something I can change locally?  Thanks for your time.  I'm new to software development (I generally do scripting/bioinformatics).  If you are too busy, no worries!  Thanks!  @sjagoe

**Comment by untitaker** [comment]
If you want to try #240:

    git clone https://github.com/mitsuhiko/click
    cd click
    git fetch origin pull/240/head:tmp
    git checkout tmp
    python setup.py install

**Comment by sjagoe** [comment]
sorry, I haven't had time to come back to this yet. I'll try to revisit it this week for another fix.
