### ISSUE TITLE
Order of options / command name seems to matter

### ISSUE THREAD

**Issue by marktheunissen** [mitsuhiko/click#245]
Hello,

If I have options, it seems to be mandatory that they appear before the command name, as putting them after triggers a 'no such option' error.

Test code:

```python
import click

@click.group()
@click.option('--abc', default=2)
@click.option('--defg', default=2)
def cli(abc, defg):
    click.echo('Options passed were %s / %s' % (abc,defg))

@cli.command()
def sync():
    click.echo('Synching')

if __name__ == '__main__':
    cli()
```

This doesn't work:

```bash
$ test.py sync --defg=6
Options passed were 2 / 2
Error: no such option: --defg
```

This works:

```bash
$ test.py --defg=6 sync
Options passed were 2 / 6
Synching
```

It may be that the options must come before the command, but then for example I see in one of the tests:

```python
Usage: foo test [OPTIONS]
```

And I also have received a message before saying `Usage: <script> command [OPTIONS]` where the options were listed last in the list.

Perhaps just a better error message instead of `no such option`?

Thanks!
Mark

**Comment by mitsuhiko** [comment]
This is intentional.
