### ISSUE TITLE
Prompts with functions

### ISSUE THREAD

**Issue by warsamebashir** [mitsuhiko/click#248]
Can we pass functions to the prompt in http://click.pocoo.org/3/options/#prompting , I ask because i can't seem to find a way to change the type of prompt I can make. I want a date prompt or a multiple prompts so I want to take over as a function and use the standard python prompting capabilities if that is possible?

**Comment by mitsuhiko** [comment]
Just call `click.prompt()` yourself if you need more complex cases.
