### ISSUE TITLE
Should passing nargs=-1 to click.option produce an error?

### ISSUE THREAD

**Issue by pjbaker** [mitsuhiko/click#261]
Setting `nargs=-1` is [supported for arguments](http://click.pocoo.org/3/arguments/#variadic-arguments) but [not for options](http://click.pocoo.org/3/options/#multi-value-options).

However, using `@click.option(..., nargs=-1, ...)` does not currently produce an error. Should it?

**Comment by untitaker** [comment]
Closing as duplicate.
