### ISSUE TITLE
is raise SystemExit(exit_code) the right way to return a non-zero exit status?

### ISSUE THREAD

**Issue by aconrad** [mitsuhiko/click#270]
I would like to control the exit status of a command. I saw that different exceptions are available from Click which are mostly used for bad command line usage.

I just want a clean exit for a properly ran command (with no `Abort!` message). I ended up using `raise SystemExit(1)`. Is this the proper way of doing it? I was thinking that it'd be nice if the return value of the command would be the exit status.

```python
@pycobertura.command()
@click.argument('cobertura_file1')
@click.argument('cobertura_file2')
def diff(cobertura_file1, cobertura_file2):
    """compare two coverage files"""
    cobertura1 = Cobertura(cobertura_file1)
    cobertura2 = Cobertura(cobertura_file2)
    reporter = DeltaReporter(cobertura1, cobertura2)

    report = reporter.generate()
    click.echo(report)

    # non-zero exit code if line rate worsened
    exit_code = cobertura1.line_rate() > cobertura2.line_rate()
    raise SystemExit(exit_code)  # or `return exit_code`?
```

**Comment by scharissis** [comment]
Why not use the regular python site module exit()?
It works great for me.

https://docs.python.org/2/library/constants.html#exit

**Comment by untitaker** [comment]
@scharissis:

>They are useful for the interactive interpreter shell and should not be used in programs.

Use ``sys.exit`` instead, or just raise the exception manually, either way is fine.

**Comment by gst** [comment]
Hi,

@scharissis  @untitaker 

I don't create a new issue as my question is totally linked to this one : 

why does click so apparently "force" the return code of the function to 0 and ignore the given return value?

well actually it's not that it force the return value to 0, it doesn't return but executes (force?) sys.exit() itself. with 0 whatever is the return value you actually returned from the function so..

I mean : wouldn't it be ok/better that it uses the returned value from the function to sys.exit() ?

Thx for any info.

**Comment by untitaker** [comment]
@gst You're mixing up raising `SystemExit` with function return values here, so it's not really clear what you're asking. The return value of the function was never something that Click honored.

**Comment by gst** [comment]
hi,

well.. I wasn't 100% clear effectively.

My question is so:

couldn't `click` use the return value of a _click.Command_ decorated function when it returns, like `diff` here above,  and to sys.exit() that value ? That is just `return cobertura1.line_rate() > cobertura2.line_rate()` for the above.

I (quickly) checked the documentation and didn't find a clear statement (but I could have missed it) about how to it is supposed to be handled (the process exit code of a click.Command).

Thx.

**Comment by untitaker** [comment]
Yeah click ignores that. You should use sys.exit instead.

On 5 January 2017 16:21:37 CET, "Grégory Starck" <notifications@github.com> wrote:
>hi,
>
>well.. I wasn't 100% clear effectively.
>
>My question is so:
>
>couldn't `click` use the return value of a _click.Command_ decorated
>function when it returns, like `diff` here above,  and to sys.exit()
>that value ? That is just `return cobertura1.line_rate() >
>cobertura2.line_rate()` for the above.
>
>I (quickly) checked the documentation and didn't find a clear statement
>(but I could have missed it) about how to it is supposed to be handled
>(the process exit code of a click.Command).
>
>Thx.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/270#issuecomment-270669282

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NiklasRosenstein** [comment]
> Yeah click ignores that. You should use sys.exit instead.

I think the question is about *why* Click ignores that. That would be quite convenient, and IMHO returning the exit code makes the code look cleaner than using `sys.exit()` (one of the reasons might be that `return` is usually highlighted in editors and you will notice it much easier than `sys.exit()` and it gives you a visual indicator of "function can end here").

**Comment by untitaker** [comment]
I tend to agree, if you open a complete PR with doc updates and tests and changelog, I will merge it.

On 5 April 2017 16:48:10 CEST, Niklas Rosenstein <notifications@github.com> wrote:
>> Yeah click ignores that. You should use sys.exit instead.
>
>I think the question is about *why* Click ignores that. That would be
>quite convenient, and IMHO returning the exit code makes the code look
>cleaner than using `sys.exit()` (one of the reasons might be that
>`return` is usually highlighted in editors and you will notice it much
>easier than `sys.exit()` and it gives you a visual indicator of
>"function can end here").
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/pallets/click/issues/270#issuecomment-291885338

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by WeatherGod** [comment]
I am confused. The documentation at https://click.palletsprojects.com/en/7.x/commands/#command-return-values states quite clearly, to me at least, that command return values are honored. Why is it that when I use `CliRunner.invoke()` that I don't get the exit_code that I returned from my command-decorated function? Perhaps this is a documentation issue, but it would be nice if the result of `CliRunner.invoke()` was consistent with what happens when I use the entry_point at the command-line.

**Comment by WeatherGod** [comment]
relatedly, when one does console_script entry points, you use `return` to indicate the exit code. So, as someone who has been used to that behavior, this was quite surprising.

**Comment by untitaker** [comment]
@WeatherGod I think that pretty much depends on how you wired up `CliRunner.invoke()` with your `console_script`. From what I can tell `CliRunner.invoke()` is supposed to return an int

**Comment by PREM1980** [comment]
> Why not use the regular python site module exit()?
> It works great for me.
> 
> https://docs.python.org/2/library/constants.html#exit

Hello,

How do I handle click.abort exception in my code. If abort exception happens I need to close my queue that i am consuming. Kind of customize the abort exception.
