### ISSUE TITLE
Variadic options

### ISSUE THREAD

**Issue by alexbw** [mitsuhiko/click#271]
Would be incredibly convenient to have support for variadic options. 

```python
@click.command()
def command(**kwargs):
    click.echo(kwargs.keys())
```

Would like to be able to do
```
> binary command --newarg1=3 --newarg2=4
['newarg1','newarg2']
```

Can't figure out a way to do this yet.

**Comment by mitsuhiko** [comment]
Going to close this, you can use this in 4.0.
