### ISSUE TITLE
Accepting arguments over a UNIX pipe

### ISSUE THREAD

**Issue by alexbw** [mitsuhiko/click#272]
I have a command like this, which will update data item 1, with some user-provided JSON
```
tool update-data 1 '{"name": "A New Name"}'
```

Sometimes, the JSON the user has to provide can get quite long, so it makes sense to provide it via a file. I'd like to do 
```
tool update-data 1 < data.json
```
or
```
cat data.json | tool update-data 1
```

The way I get around this right now is by explicitly handling whether or not any values were provided to the optional second argument, and if not, trying to pull from stdin, like so:

```
    if data == "":
        if select.select([sys.stdin,],[],[],0.0)[0]:
            for line in sys.stdin:
                if not line: 
                    break
                data += line
        else:
            click.echo("No data provided.")
            return
```

I'm not sure if it's out of scope for click to transparently accept stdin or a string to a last argument.

**Comment by untitaker** [comment]
Yeah I think this is out of scope... You probably want to write a custom converter that takes either a filename, JSON, or ``-`` for stdin. Click's ``File`` can deal with half of it.
