### ISSUE TITLE
Argument metavar parameter not used with exception message

### ISSUE THREAD

**Issue by rsyring** [mitsuhiko/click#273]
## The Code

``` python
@app.command('mssql', short_help='Backup Microsoft SQL database(s).')
@click.argument('backup_type', metavar='type')
def mssql(backup_type):
    click.echo('Running the backup...')
```

## Expected Output

``` console
(backupdb)rsyring@loftex:~/projects/backup-db-src$ backupdb mssql
Usage: backupdb mssql [OPTIONS] type

Error: Missing argument "type".
```

## Actual Output

Note that the metavar parameter is used in "Usage" but not when notifying the user about the missing argument:

``` console
(backupdb)rsyring@loftex:~/projects/backup-db-src$ backupdb mssql
Usage: backupdb mssql [OPTIONS] type

Error: Missing argument "backup_type".
```

**Comment by mitsuhiko** [comment]
Good point, i changed this for 4.0.

**Comment by rsyring** [comment]
Thanks for the fix.  I saw your post on joining Sentry.  I hope that allows you to work more in the OSS world, I really appreciate a lot of the project you put out.  Will also be checking out Sentry, I've been looking for something like that.
