### ISSUE TITLE
Is there a way to write django's management commands with click?

### ISSUE THREAD

**Issue by svetlyak40wt** [mitsuhiko/click#274]

**Comment by untitaker** [comment]
Not sure what you're asking here. Did you try it?

**Comment by svetlyak40wt** [comment]
Because django's management commands are autodicovered by `manage.py` utility. I didn't digged into django's internals yet so not sure how autodiscovery works.

**Comment by untitaker** [comment]
If you are able to retrieve a list of commands, you can add commands to click programatically, yes.

**Comment by Suor** [comment]
The original question was not about adding django commands to click, but writing django command with click and not with built-in django messy boilerplate.

**Comment by untitaker** [comment]
By "adding to click" I meant "adding to a click application". Either way, I think this is better suited for StackOverflow.

**Comment by GaretJax** [comment]
@svetlyak40wt and @Suor, I just released version 1.0 of django-click, to solve exactly this issue. Check it out at https://github.com/GaretJax/django-click and https://pypi.python.org/pypi/django-click. Feedback welcome!
