### ISSUE TITLE
Merge group into another

### ISSUE THREAD

**Issue by dmitrybelyakov** [mitsuhiko/click#275]
Hi,

I have two cli groups and would like to merge one into another and make it available under a given name.
Something like this:

```python
./cli.py cli2 cli2-command
```
or more specifically:
```python
./manage.py db init # db is a group
```

Ideally I'm looking for a way to 'mount' a certain group of commands under another group. Is that possible?

**Comment by mitsuhiko** [comment]
Yes that is possible and also documented.  Just use `add_command`.
