### ISSUE TITLE
Support for logging-setup

### ISSUE THREAD

**Issue by dploeger** [mitsuhiko/click#277]
I find click wonderful as it simplifies all my cli-related code lines.

What I also do besides argument checking (what click does) is setting up the logging (using Python's logging-facilities) according to certain parameters.

I'd find it great, if click would also do that. Namely...

* Understand -q for quiet mode (call **logging.basicConfig(level=logging.CRITICAL)**)
* Understand -v for verbose mode (call **logging.basicConfig(level=logging.INFO)**)
* Understand -d for debug mode (call **logging.basicConfig(level=logging.DEBUG)**)

Call **logging.basicConfig(level=logging.ERROR)** without any specific parameter.

That could be done using another decorator like @simplelog.

**Comment by kissgyorgy** [comment]
I think it's unnecessary to have three switches for the same feature. How py.test does it, also it appears in click documentation: with count for e.g. -v, so like `$ command -vvv` is more verbose than `$ command -vv`

**Comment by dploeger** [comment]
I'll add that flavor to my pull request.

**Comment by kimvais** [comment]
Please merge this - @click.simplelog(flavor='vvv') is pretty much what I need.

**Comment by untitaker** [comment]
If you're interested in this, there is a basic implementation at https://github.com/click-contrib/click-log. Patches for other option flavors are welcome!
