### ISSUE TITLE
A command without any name and multiple arguments

### ISSUE THREAD

**Issue by karan** [mitsuhiko/click#280]
Sorry for being vague with the title but I'm not sure what the technical term for this is.

Basically, I have a script called `joe.py` which has a bunch of command.

```bash
$ python joe.py ls    # ls is a command in a group
````

Now I want to support dynamic command too. Something like this:

```bash
$ python joe.py abc    # not defined explicitly, but should be handled
$ python joe.py abc def    # not defined explicitly, but should be handled in the same way as ^
````

I have a list of strings of these "dynamic command".

Basically, it's an anonymous command with 1 or more options (`abc` and `def` in this case) and some explicitly defined commands as well (`ls` in this case).

This is how I'm defining my command:

```python
@click.command(name='ls')
def ls():
    _print_filenames()


@click.group()
def cli():
    pass

cli.add_command(ls)

if __name__ == '__main__':
    cli()
```
How do I do this?

**Comment by mitsuhiko** [comment]
You can subclass a group: http://click.pocoo.org/3/advanced/#command-aliases

**Comment by MinchinWeb** [comment]
Updated link for anyone else who finds this: http://click.pocoo.org/6/advanced/#command-aliases
