### ISSUE TITLE
How to turn around click and use it to validate function call instead of CLI command ?

### ISSUE THREAD

**Issue by tinkerbotfoo** [mitsuhiko/click#284]
I want create individual scripts which would act as a CLI command and as well as a function/class that can be imported and called from other scripts using it.

I love the way i can decorate the parameters in click.

Is there a way to turn around and also make click to apply its its functionality to functions that can be called from other python scripts ?

Note: i briefly though i could achieve the functionality by using the CliRunner from click.testing but i have my doubts. Also it is mentioned in the documentation that it is not thread safe

**Comment by untitaker** [comment]
No, this is vastly out of scope for Click.
