### ISSUE TITLE
click.Path expanduser

### ISSUE THREAD

**Issue by ovanes** [mitsuhiko/click#287]
Would be great to introduce an additional flag: `expanduser` into the constructor and use the `os.path.expanduser` (https://docs.python.org/2/library/os.path.html#os.path.expanduser) capability, so that one can pass a file location in the form of: `~/what-everfile.ext` or `~someuser/what-everfile.ext`

Thanks for the great lib!

**Comment by dsully** [comment]
+1

**Comment by untitaker** [comment]
This should be expanded by the shell. I don't know of any GNU command that does this.

**Comment by untitaker** [comment]
Also, it's easy to create your own type if you need this.

**Comment by sephii** [comment]
@untitaker suppose the value comes from a configuration file for example, or that you want to use `~` in the default value, then you won't have any expansion.

**Comment by untitaker** [comment]
Ok, I agree with the point about the default value. How does click have anything to do with configuration files though?

**Comment by ovanes** [comment]
@untitaker Unfortunately it's not always obvious for user what is shell and what is not shell. Just an example: In good will I just put naively some path parameter to click executable into PyCharm as startup params. It was passed as is. At this point I was not really thinking: is the command run through the shell or not. IMO click stands for usability. That's not usable that I have to distinguish when shell is created and when not.

The other point here is to create a class. This is what I did. The only question is: we have about 80 Python projects there. About 20 of them use click. Should I copy paste that code? Or should I just for that case create click-extensions library with one tiny class being there? Or should I create a common-utils library which contains all the garbage that's not worth to be put into a separate lib? In that case all 80 projects are going to depend on common-lib and have all the dependencies common depends on => 80 projects are going to depend on click. What's the solution?

And one last thing: ``os.path.expanduser`` seems to be harmless, if there is a ``~`` at the beginning of the string it is expanded, otherwise the old string is returned. Make that behaviour optional if you fear the existing code might break.

**Comment by untitaker** [comment]
>In good will I just put naively some path parameter to click executable into PyCharm as startup params.

That is maybe a usability issue in PyCharm. In your opinion Click stands for usability, but that wrongly implies that the behavior you're proposing is enhancing it overall. Yes, for the aspect you're mentioning it does, but what about the case where the user actually wants to point its CLI tool to a file called ``~asdf``? If you tab-complete that name in bash, it will correctly expand this to ``command \~asdf``. If the user hits enter, at this point click's current behavior behaves correctly. With your proposal, it doesn't. Also, this behavior is **literally what every other coreutils tool does**. Usability requires consistency and predictability.

>Should I copy paste that code?

No, you should delete it. This is absolutely wrong behavior. If you want to work around PyCharm's current behavior, use ``sh -c 'actual_command'`` or something like that, but don't introduce nonstandard behavior into some of your CLI tools.

**Comment by ovanes** [comment]
Well, I partially agree. First of all, I suggested to make that parameter optional. On the other hand the behaviour you describe, is broken as well. It only works if user hits tab-completion, if not shell is going to treat that not as a file name, but as a home directory of user ``asdf``. And if you insist on consistency, you can define that click.Path handles file names the same way as the shell does. In a shell you are not forced to tab-complete you can also write out ``\~`` and you are fine.

**Comment by untitaker** [comment]
>It only works if user hits tab-completion, if not shell is going to treat that not as a file name, but as a home directory of user asdf

The average shell user *knows* that `~foo` without single-quotes resolves to foo's homedir.

>And if you insist on consistency, you can define that click.Path handles file names the same way as the shell does

That's not what I mean by consistency. The consistency lies in the fact that no coreutils tool expands `~` to home directories, so click shouldn't either. If you define consistency to be the behavior that the paths are expanded twice, first by the shell and then by click, then the user can't point the CLI command to a file with `~` in it anymore.

>It is also strange, that click.Path supports envvar resolution, why that?

Where did you get that from?

**Comment by ovanes** [comment]
Yes, I mixed up with param's value can be taken from the envvar. You are right. But I am still not convinced with other points. Why does Pass supports these configurations:

* exists – if set to true, the file or directory needs to exist for this value to be valid. If this is not required and a file does indeed not exist, then all further checks are silently skipped.
* file_okay – controls if a file is a possible value.
* dir_okay – controls if a directory is a possible value.
* writable – if true, a writable check is performed.
* readable – if true, a readable check is performed.
* resolve_path – if this is true, then the path is fully resolved before the value is passed onwards. This means that it’s absolute and symlinks are resolved.

And can't introduce one more:

* os_expanduser 

Do you really think interface is bloated than?

**Comment by mitsuhiko** [comment]
This is not supposed to be done by applications only by the shell.  I have no idea why this keeps coming up.  It's a terrible idea to have applications expand this for arguments, that's not their purpose.  It would make it impossible to use a folder named `~` for instance.

**Comment by jkinred** [comment]
Old issue, but this ticket ranks high when searching for the issue of default values as per comment by @sephii above.

For default values just expand the home dir whhen declaring the default:

```
@click.option('--config', type=click.File(),                                                                                                                                                                       
              default=os.path.join(os.path.expanduser("~"), ".yourapp.yaml"))
```
