### ISSUE TITLE
Update documentation on virtual environments for python3

### ISSUE THREAD

**Issue by wil93** [mitsuhiko/click#289]
I wonder whether the documentation should be updated for the "python3" use-case. The documentation currently advises to install virtualenv, which is integrated (as `pyvenv`) in python3. That also makes it not necessary to install pip anymore.

The part from `If you are on Mac OS X or Linux..` to `..but without the sudo prefix` could then be removed (or, more likely, "framed" in a note that says "if you're using python2"). Also the `$ virtualenv venv` part should be `$ pyvenv venv` for python3.

If you believe that this should be done, I could work on it and open a PR.

**Comment by mitsuhiko** [comment]
Strong -1 on this.  `pyvenv `works differently than virtualenv and I do not want to have to consider this.  Using `pyenv` should only be something for experienced developers, everyone else should be guided through using `virtualenv`.
