### ISSUE TITLE
A completely global ctx object

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/click#292]
As discussed with @mitsuhiko in IRC, Click should support a global context object, for the same reason they're in Flask: Explicitly passing on the context object to utility functions is extremely verbose.

https://github.com/untitaker/vdirsyncer/blob/master/vdirsyncer/doubleclick.py implements this in some way. Note that unlike Flask, this object is not local to the current thread. That wouldn't make much sense for CLI tools anyway.

**Comment by kissgyorgy** [comment]
:+1: I basicly decorate every single command with @pass_context :)

**Comment by dsully** [comment]
+1

**Comment by RonnyPfannschmidt** [comment]
this is definitively needed - else something like the reline helper we have in pylibs terminalwriter cant be implemented

(i started a experiment porting pylib and pytest to click)

**Comment by untitaker** [comment]
Everybody who +1'd this, please check out this PR: https://github.com/mitsuhiko/click/pull/354

I'd like to get early feedback on the exact API (`click.ctx`). Is this ok? Does the bool behavior make sense too or should the user catch exceptions?

**Comment by untitaker** [comment]
This is somewhat implemented with https://github.com/mitsuhiko/click/pull/379. I don't like the implementation at all, but it's there if you need it.

Except for the part where it's thread-local and therefore not useful for multithreaded applications.

**Comment by untitaker** [comment]
I think the idea of having a completely global context could be pursued as an idea for a third-party package (https://github.com/click-contrib).

But instead of simply patching click's context object to be global, I'd like to provide a custom threading class that automatically inherits the context from the parent thread, perhaps even as a monkeypatch onto `threading`.

**Comment by untitaker** [comment]
https://github.com/click-contrib/click-threading
