### ISSUE TITLE
Execution from a virtualenv, similar to pipsi?

### ISSUE THREAD

**Issue by nfarrar** [mitsuhiko/click#296]
[Pipsi](https://github.com/mitsuhiko/pipsi) wraps virtualenv, allows scripts to be executed globally, automatically activating & deactivating the necessary virtualenv on demand. Is it possible to do something similar with click?

Right now I'm working on some scripts that use click as an interface with setuptools integration for my package. While developing, I'm using a virtual environment - so the commands are only available while that virtual environment is activated. Once the script is done, the commands should be available globally (so it'll need to be installed globally, _not_ in the virtual environment), however this is going to install a whole lot of dependences to the OS python, and will likely collide with other stuff.

So, similar to pipsi (mentioned above) is there anyway to make the commands available globally, while keeping the dependencies for commands isolated to a virtualenv?

**Comment by davidism** [comment]
You don't need to activate a virtualenv to execute binaries within it, just point at the binary directly.

    $ /home/david/.virtualenvs/py3/bin/my_app

**Comment by nfarrar** [comment]
Thanks, I'll give that a try.

**Comment by hartror** [comment]
My solution for this was installing a script likethis into /usr/local/bin/.

```
#!/bin/bash -e
/home/roryhart/.virtualenvs/foo/bin/foo "$@"
```

**Comment by mitsuhiko** [comment]
Closing this, not sure why this is a ticket :)
