### ISSUE TITLE
[CliRunner] Documentation for options

### ISSUE THREAD

**Issue by traxair** [mitsuhiko/click#299]
Hey, nice work on this lib!
Could you add somewhere in the doc that to use options you just have to set it as regular arguments in the CliRunner?

e.g
```
runner = CliRunner()
runner.invoke(command, ['argument', '--dry-run'])
```

This could be a nice addition to the [testing page](http://click.pocoo.org/3/testing/)

**Comment by 21364783** [comment]
Hi, there, I have the same confusion. Cloud you help me with #314

**Comment by untitaker** [comment]
Fixed by https://github.com/mitsuhiko/click/pull/378
