### ISSUE TITLE
Is there a way to make an option dependent on another option

### ISSUE THREAD

**Issue by shaumux** [mitsuhiko/click#308]
I am trying to build an multicommand application where the username and password options are optional in the cli and if not provided will be parsed from a file.
Now what I want to do is if someone passes the option for the username then they must also use the password option.
Another thing I would like to check is if someone passes the password option then he also needs to pass the username.
If I use a callback the other options passed seem not be visible to the callback.

**Comment by mitsuhiko** [comment]
You can use callbacks for that.  Since they fire late you can check other parameters as they are stored on the passed context object.

**Comment by thijsvandien** [comment]
Today I was wondering about the same thing. Would you consider making the case of related parameters easier to implement? I can imagine `required` to accept a callable as well, or some kind of grouping construct. The issue isn't really to check for this myself and throwing some exception. It's the uniformity that is soon lost when the error message becomes a custom one.
