### ISSUE TITLE
Trailing 'None' in usage/error when a required argument or option is omitted

### ISSUE THREAD

**Issue by geowurster** [mitsuhiko/click#312]
Executing a CLI command and omitting a required argument or option causes 'None' to be appended the the error message.

Consider the following CLI:

```python
#!/usr/bin/env python


import click


@click.command()
@click.argument('infile')
@click.option('-o', '--outfile', required=True)
def main(infile, outfile):

    pass


if __name__ == "__main__":
    main()

```

Executing without any arguments yields the following output and a trailing 'None' on the last line:

```console
(venv)Captain:click kwurster$ ./trailing-none.py 
Usage: trailing-none.py [OPTIONS] INFILE

Error: Missing argument "infile".None
```

Executing with the required `infile` argument triggers an error for the required `--outfile` argument, which also contains a trailing 'None' on the last line:

```console
(venv)Captain:click kwurster$ ./trailing-none.py something
Usage: trailing-none.py [OPTIONS] INFILE

Error: Missing option "-o" / "--outfile".None
```

**Comment by homeworkprod** [comment]
I assume this has been introduced in 64f57fe.

The new `MissingParameter` class accepts a keyword argument `message` which defaults to `False` ([line 99](https://github.com/mitsuhiko/click/blob/64f57fea3a2d82b590e93fe29cb85c87be08a8a4/click/exceptions.py#L99)).

The message is passed upwards to `ClickException` which assigns it to an instance member of the same name ([line 16](https://github.com/mitsuhiko/click/blob/64f57fea3a2d82b590e93fe29cb85c87be08a8a4/click/exceptions.py#L16)).

The value is used starting in [line 118](https://github.com/mitsuhiko/click/blob/64f57fea3a2d82b590e93fe29cb85c87be08a8a4/click/exceptions.py#L118), but only overwritten if a `msg_extra` is found (which seems to be only the case of a "choice" type; all other types use the default implementation of the `get_missing_message` method, which is empty (i. e. returns `None`).

The explicit checking for non-`None`-ness in [line 13](https://github.com/mitsuhiko/click/blob/64f57fea3a2d82b590e93fe29cb85c87be08a8a4/click/exceptions.py#L13) suggests that `None` is a valid (or at least tolerated) message.

So, while the fix suggested in [PR 313](https://github.com/mitsuhiko/click/pull/313), _might_ not be at the best place, I think it's not too far off.

_Maybe_ the fourth parameter was meant to read `msg_extra`. Anyway, it seems to me, the appending of that extra seems to be done twice/redundantly, and one part should be removed altogether.

**Comment by nchammas** [comment]
For the record, I am seeing this as well on Click 4.0.

**Comment by hjacobs** [comment]
I'm seeing this as well and it would be nice to get it fixed as my CLI users notice the "None" too ;-)

**Comment by untitaker** [comment]
Fixed in master, will be released with 4.1

**Comment by danielfrg** [comment]
Thanks for the fix!

When is 4.1 scheduled for release? I am releasing an app and i would like to have the latest click and have this fix.

**Comment by geowurster** [comment]
@danielfrg this fix is purely cosmetic so if you don't require any features introduced in 4.1 just list `click>=4.0` in your requirements, or just `click` depending on which features you're using.  When click 4.1 is released your users can get it with `pip install click --upgrade` and you don't have to do anything to your app.

**Comment by untitaker** [comment]
@danielfrg Unfortunately I don't think 4.1 will be released anytime soon, as that bug (and others which are fixed in that version) are too minor to warrant a release.

**Comment by danielfrg** [comment]
Thanks for the info and suggestions, maybe I'll end up using click 3.0 since i like to have frozen versions `==` instead of `>=`.

Thanks!
