### ISSUE TITLE
Remove termwidth-dependent line wrapping?

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/click#317]
It is the cause for a lot of bugs, hard to implement and AFAIK there's no other CLI tool doing this. It also makes custom formatting very hard as it's no longer possible to design the output for a fixed width of 80-ish chars.

**Comment by mikenerone** [comment]
There are a couple of existing approaches that might do what you need:

1. [Per the documentation, you can prevent wrapping](http://click.pocoo.org/4/documentation/#preventing-rewrapping) by prefixing each paragraph of your help text with a `\b`.

2. You can leave the wrapping on, but still achieve consistency by telling Click to _always_ assume the terminal width is 80:
```python
@click.command(context_settings={'terminal_width': 80})
def my_cli():
    ...
```

**Comment by untitaker** [comment]
Thanks, I am already aware that I can override the terminal width. My point rather was that the whole feature is unique to click and isn't found in any other application AFAIK.

**Comment by mitsuhiko** [comment]
You can already force the terminal width as mentioned.  The behavior is consistent with other tools such as `hg`.
