### ISSUE TITLE
echo_via_pager in windows occasically prints gibberish

### ISSUE THREAD

**Issue by darikg** [mitsuhiko/click#319]
I've trying to track down the source of a bug in another program amjith/pgcli#183 and have narrowed it down to click.echo_via_pager, only in Windows. The following seems to reproduce it:

```
import click

bad_str = '''+-------------------+---------+
|   generate_series |   round |
|-------------------+---------|
|                 1 |       1 |
|                 2 |       0 |
|                 3 |       1 |
|                 4 |       0 |
|                 5 |       1 |
|                 6 |       0 |
|                 7 |       1 |
|                 8 |       0 |
|                 9 |       1 |
|                10 |       0 |
+-------------------+---------+
SELECT 10'''

click.echo_via_pager(bad_str)
```
which prints
```
?????????????????+?????????+?????????????????????++++++++??+++???++++++++'?+++%??++++++++??+++???++++++++??+++%??++++++++`?+++???++++++++??+++%??++++++++??+++???++++++++??+++%??++++++++<?+++???+++++++?%?+++%??????????????????????
```

instead of the expected `bad_string` contents. Small changes in the value of `bad_string` fix the problem. I put a debugger breakpoint [here](https://github.com/mitsuhiko/click/blob/0d9731e97c9af9e5b0f5fd8421aeb0184ad42b70/click/_termui_impl.py#L321) and found that encoding was the same (cp437) for both buggy and bug-free strings. However opening the temporary text file created revealed a difference -- notepad.exe was opening the bugged versions as Unicode, showing this as the contents:

```
(⴫ⴭⴭⴭⴭⴭⴭⴭⴭⴭ⴫ⴭⴭⴭⴭਫ⁼†敧敮慲整獟牥敩⁳⁼†潲湵⁤੼⵼ⴭⴭⴭⴭⴭⴭⴭⴭⴭ⴫ⴭⴭⴭⴭ੼⁼††††††††‱⁼†††‱੼⁼††††††††′⁼†††‰੼⁼††††††††″⁼†††‱੼⁼††††††††‴⁼†††‰੼⁼††††††††‵⁼†††‱੼⁼††††††††‶⁼†††‰੼⁼††††††††‷⁼†††‱੼⁼††††††††‸⁼†††‰੼⁼††††††††‹⁼†††‱੼⁼†††††††ㄠ‰⁼†††‰੼⴫ⴭⴭⴭⴭⴭⴭⴭⴭⴭ⴫ⴭⴭⴭⴭਫ䕓䕌呃ㄠਰ
```
whereas other text editors like notepad++ correctly displayed the original text.

So I think what's happening is that more.exe is incorrectly opening the temporary text files as Unicode.

**Comment by darikg** [comment]
Yup, changing the default pager (by setting the environmental variable PAGER) fixes the issue. So not a bug with click.

**Comment by untitaker** [comment]
Just curious, which Python version is this?

**Comment by darikg** [comment]
this was python 2.7
