### ISSUE TITLE
Document how to make envvar defaults behave like normal defaults

### ISSUE THREAD

**Issue by pfmoore** [mitsuhiko/click#324]
When an option is given a default, the prompt for that option changes to say ```Enter <option> [default]:``` and the default is used unless the user overrides it. Defaults from environment variables or from the context ```default_map``` do not behave like this, however, but instead *replace* the prompting behaviour, so they behave more like user input than a default.

Would it be possible to at least add an option to use environment or ```default_map``` defaults in the prompt, rather than the current behaviour (or is there a way of doing this already which I haven't spotted)?

Here's an example program:

```python
import os
from configparser import ConfigParser
import click
import click.utils

@click.command()
@click.option('--foo', default='Hello', envvar="FOO", prompt="Enter foo")
def cli(foo):
    print("Foo is", foo)

if __name__ == '__main__':
    appini = os.path.join(click.utils.get_app_dir('Clicker'), 'clicker.ini')
    dflt = {}
    if os.path.exists(appini):
        cp = ConfigParser()
        cp.read(appini)
        if cp.has_section('defaults'):
            dflt = cp['defaults']

    cli(default_map=dflt)
```

The intent here is that if the user says ```clicker --foo XXX``` no prompt is issued, but otherwise the user is prompted, with the default coming from the environment, or the application ini file, or the hard-coded "Hello" (in that order of preference).

**Comment by pfmoore** [comment]
Never mind, the behaviour I am looking for can be implemented by providing a callable that does the lookups I want for the ```default``` argument to the option.

**Comment by pfmoore** [comment]
... although it might be worth adding an example to the documentation explaining the 2 different approaches.

**Comment by untitaker** [comment]
I was about to suggest:

* Passing a callable as default
* Subclassing Option

**Comment by untitaker** [comment]
Reopening for docs

**Comment by pfmoore** [comment]
I've submitted a PR for a change to the docs, in #325

**Comment by untitaker** [comment]
Ok, I think I can close this now, since the PR has been merged.
