### ISSUE TITLE
Multiple types

### ISSUE THREAD

**Issue by dudektria** [mitsuhiko/click#328]
I am interested in having options supporting the following cases:

    --option=yes
    --option=false  # and all the other cases supported by Boolean.
    --option=achoice
    --option=anotherone  # support all within a group as Choice does.

    --int=no  # again, Boolean supported.
    --int=23  # but an IntRange as well.

Is it possible to chain different types? Of course `Choice(['yes', 'true', 'no', 'false', 'achoice', ...])` works, but I believe it looks ugly on the help page (a help usage such as `BOOL or [achoice|...]` seems optimal to me).

**Comment by untitaker** [comment]
Turns out this works pretty well:

    import click

    def validate_foo(ctx, param, value):
        try:
            return int(value)
        except ValueError:
            return value

    @click.command()
    @click.option('--foo', callback=validate_foo)
    def cli(foo):
        print(repr(foo))

    cli()

`foo` will be an int if it can be parsed into one, else it's a string. That said, I don't think doing this is a great idea for UI.

**Comment by dudektria** [comment]
Thanks for your reply.

> That said, I don't think doing this is a great idea for UI.

Why so?

**Comment by untitaker** [comment]
Perhaps it depends, but I suspect that having not a single possible type for an option only adds to complexity. What's your usecase?

**Comment by dudektria** [comment]
I have options which can be either activated or specifically tuned for a task. I am writing a "universal input generator" for a couple quantum chemistry packages.

As an example, one such package specifies an approximation called "resolution of identity". It comes in many flavours. We have the following keywords: RI, NoRI (turned off), RIJK and RIJCOSX. I would like to have a boolean-like behaviour for RI/NoRI, but Choice()-like behaviour for the other two like so:

    --ri       # RI
    --ri=yes   # RI
    --ri=no    # NoRI
    --ri=false # NoRI
    --ri=jcosx # RIJCOSX
    --ri=jk    # RIJK

What do you think, can I do better/simpler?

**Comment by untitaker** [comment]
I see. No, I don't think you can do better. However, the first line won't be possible -- either options are flags or they aren't. See #370 for the rationale.

Take a look at `click/types.py`, you could write a generic `ChainType` that tries the `convert` methods of multiple types.

**Comment by dudektria** [comment]
I haven't thought about that (regarding `--ri` and `--ri=yes`).

And thanks for the suggestion. I'll try to figure out a way to do it in a more consistent way.
