### ISSUE TITLE
Behavior equivalent to fabric's local function

### ISSUE THREAD

**Issue by charlax** [mitsuhiko/click#337]
Any interest in me building an equivalent to fabric's `local`'s function?

It's just a basic `os.system` that check if the command succeeded, and exists if it did not, basically. I guess it would go in the shell utils.

**Comment by untitaker** [comment]
I personally don't think this should be part of Click. Click is a library to *build CLI interfaces*, not a general scripting toolbox.

I think `subprocess` fills this need quite well, if you're looking for something fancier, I suppose `sh` might be an option too (although I heavily dislike its magic).

**Comment by charlax** [comment]
I guess that makes sense. I was thinking this was similar to the shell color package, but it's true that shell colors are pretty coupled to CLI interfaces. I would say though that the intelligent opening feature definitely is less about CLI interfaces, and more about scripting toolbox. Same thing for `click.edit`.

I'd say that it's a pretty ubiquitous use case.

I also dislike `sh`'s magic.

**Comment by untitaker** [comment]
Closing this because out of scope. Perhaps fabric could better integrate (or vice-versa) in the future.
