### ISSUE TITLE
click.File() produces an iterator but click.open_file() does not

### ISSUE THREAD

**Issue by geowurster** [mitsuhiko/click#338]
When setting an argument or option's type to `click.File()` the resulting instance of `TextIOWrapper` is an iterable, but when opening `stdin` with `click.open_file()` the resulting instance of `KeepOpenFile` is not.  `KeepOpenFile` allows access to the underlying file-like object's attributes with a smarter `__getattr__()` so I'm guessing omitting `__iter__()` was accidental.

Assuming this wasn't intentional, it seems like the best solution is to add an `__iter__()` method that just does `return self`.  When the object is iterated over the underlying file-like object's `next()` or `__next__()` is automatically called via the smart `__getattr__()`.  The other solution would be to just set `__iter__` equal to the underlying file-like object's `__iter__` but that seems less intuitive and could cause problems if the underlying object lacks an `__iter__` method, although I looked through the source code and that doesn't appear to be possible.

```python
# Produces an iterable file-like object
@click.option('--infile', type=click.File())

# Does not produce a file-like object
infile = click.open_file(path)
```

**Comment by geowurster** [comment]
Sorry about all the name changes - I hit submit a little too early.

**Comment by untitaker** [comment]
Fixed by https://github.com/mitsuhiko/click/pull/342
