### ISSUE TITLE
String generation error in MissingParameter.format_message

### ISSUE THREAD

**Issue by kenr** [mitsuhiko/click#343]
When requiring a argument to be present with @click.argument('myargument', required=True), the output from Click is Error: Missing argument "myargument".**None**. 

This is because the output string created with: 

```return 'Missing %s%s%s%s' % (
            param_type,
            param_hint and ' %s' % param_hint or '',
            msg and '.  ' or '.',
            msg,
        )```

 expects msg to be set to a value but Click does not set this value.

**Comment by untitaker** [comment]
That issue is already fixed in master, https://github.com/mitsuhiko/click/pull/313
