### ISSUE TITLE
Click progressbar with multiprocessing?

### ISSUE THREAD

**Issue by endrebak** [mitsuhiko/click#349]
I want to use click to show the progress of a parallel loop.

Problem is, it does not seem to work with for loops run in parallel:
```python
with click.progressbar(strand_chromosome_tuples) as bar:
    
    chromosome_windows = workers.map(partial_count_reads_in_windows, bar)
```

This shows 100% all the time, while using a solution like this:

```python
with click.progressbar(plus_minus_dfs) as bar:
    for t in bar:
        merged_chromosome_dfs.append(workers.apply(merge_chromosome_dfs, t))
```

does not run the function in parallel.

Is there a solution?

**Comment by untitaker** [comment]
It seems that `multiprocessing.Pool` consumes the iterator completely. This is not really Click's problem.

IIRC what I did is to use `imap_unordered`, like this:

    p = Pool(...)
    results_iter = p.imap_unordered(...)
    with click.progressbar(results_iter) as bar:
        for _ in bar:
            pass

**Comment by endrebak** [comment]
Thanks. I thought this was more of an SO question, but they had no click-tag. Will try.

**Comment by untitaker** [comment]
It seems the tag is called `python-click`.
