### ISSUE TITLE
Parse a string and invoke appropriate handlers

### ISSUE THREAD

**Issue by brainysmurf** [mitsuhiko/click#361]
I have a bunch of handlers prepared with click that are invoked with the command line. But I'd like to be able to have a single importable function that takes a string as an argument, and then invoke the appropriate handler. This is to be used for batch operations, where I build a list of strings that represent command line commands. Instead of piping it out to the system, (where I would then have to parse the result) I would prefer to build these strings rather than importing the handlers.

Does click have some class that I can use for this? Closest thing I could find was CliRunner but it assumes I have the target handler available. I want to invoke the handler based on the string.

So if my app name is foo and the command is bar, I would pass my function parse the string 'foo --verbose bar --option" and it would do the same stuff that click does as if it came from the command line.

Please advise how I might go about doing this.

**Comment by untitaker** [comment]
>Closest thing I could find was CliRunner but it assumes I have the target handler available

It assumes you have the root CLI object available (the command group).

**Comment by brainysmurf** [comment]
Aha. So it was what I was looking for. You would suggest highlighting in the docs.

"CliRunner can also be used to hook up some other code to your defined groups and commands. All you need to do is pass it the root group and tack on any params."

Click is really slick.

**Comment by untitaker** [comment]
The whole CLI app is IMO treated as a single callable throughout the docs, and in the testing chapter as well. You should rarely feel the need to call a subcommand by passing it into the CLI runner directly.

I'm not sure what documentation changes you suggest -- but clarifications for the current docs are apprechiated in general.
