### ISSUE TITLE
CliRunner.invoke returns "wrong" error code when using sys.exit

### ISSUE THREAD

**Issue by torfuspolymorphus** [mitsuhiko/click#362]
`CliRunner.invoke` returns the "wrong" error code when the target function uses `sys.exit(error_string)`. Instead of a numerical code (as expected), `Result.error_code` contains the string message of the `SystemExit` exception raised by `sys.exit`. The reason is that `SystemExit.code` (which is [used by `CliRunner.invoke`](https://github.com/mitsuhiko/click/blob/master/click/testing.py#L280)) also contains that string:
```
In [1]: import sys

In [2]: try:
   ...:     sys.exit('error')
   ...: except SystemExit as e:
   ...:     print e.code
   ...:     
error
```
The [documentation of `sys.exit`](https://docs.python.org/2/library/sys.html#sys.exit) says that

> The optional argument arg can be an integer giving the exit status (defaulting to zero), or another type of object. [...] If another type of object is passed, None is equivalent to passing zero, and any other object is printed to stderr and results in an exit code of 1.

However, the actual exit code seems to be set somewhere else (and only if the `SystemExit` exception is not caught, obviously).

In my opinion, `CliRunner` should try to report the exit code that is reported to the OS. Hence, if `SystemExit.code` is not an integer, `Result.exit_code` should be 1.

I'd be happy to provide a corresponding PR if that helps.

**Comment by torfuspolymorphus** [comment]
It seems that `Result.output` also doesn't contain the error message in that case: Compare the output of 
```
import sys
import click
from click.testing import CliRunner

@click.command()
def main():
    sys.stderr.write('error')
    sys.exit(1)

runner = CliRunner()
result = runner.invoke(main, [])
print 'Output: %r' % result.output
```
with that of 
```
import sys
import click
from click.testing import CliRunner

@click.command()
def main():
    sys.exit('error')

runner = CliRunner()
result = runner.invoke(main, [])
print 'Output: %r' % result.output
```
In my opinion, `Result.output` should be the same in both cases, since both cases yield the same console output when not run via `CliRunner`.

**Comment by untitaker** [comment]
`sys.exit("...")` is IMO not a thing people ought to do, but I'd agree that `CliRunner`'s isolation layer is too thin there. I'd be happy to merge a PR:

**Comment by untitaker** [comment]
Fixed with https://github.com/mitsuhiko/click/pull/363
