### ISSUE TITLE
Subclassing Parameter

### ISSUE THREAD

**Issue by brainysmurf** [mitsuhiko/click#364]
I'm curious what might be the best way to implement "named arguments" with click. So the cli looks like this:

```
update user <string> description <string> externalid <int>
```

The idea would be to define a user argument that allowed "user joe" to be entered and then the variable user would just be the value of "joe"

I saw this in the documentation: "Other subclasses are currently not supported by design as some of the internals for parsing are intentionally not finalized." But looking at the code it looks like "type_cast_value" is the method I'd want to override.

Just wondering if this is the best way to continue.

**Comment by untitaker** [comment]
Why not use options? Arguments are positional-only.

**Comment by mitsuhiko** [comment]
Definitely unsupported as a core feature.  There be dragons with this.
