### ISSUE TITLE
Feature Request: command's prompt feature should support retry

### ISSUE THREAD

**Issue by cornfeedhobo** [mitsuhiko/click#366]
I am not sure how best to approach this yet, but it would be nice to have the ability to re-prompt the user if an input does not validate through the callback, instead of only having the option to error.

An example use case might be validating a FQDN and re-prompting if invalid.

Thanks.

**Comment by untitaker** [comment]
`click.prompt` does prompt again if the input is invalid, e.g. this:

    click.prompt('Integer', type=int)
