### ISSUE TITLE
How to define groups and commands in different files

### ISSUE THREAD

**Issue by brainysmurf** [mitsuhiko/click#368]
I'd like to organize my commands and groups into different files, like one for each group that I branches off the root groups, but it's not clear from the docs if I can do this, or if not, that I cannot. 

I tried this

```
import cli    # the root group, also defined as the "callback" for entry_points

@cli.command()
def version:
    print('hello, version')
```

But when that code is placed into a file other than the one that cli is already in, and execute it from the command line, it does not work (nor does bash completion work).

I'm just wondering if anyone could shed some light. I realize this is probably more of a setuptools query.

**Comment by a-sk** [comment]
Maybe [custom-multi-commands](http://click.pocoo.org/4/commands/#custom-multi-commands) is what you are looking for?

**Comment by untitaker** [comment]
Subcommand:

    import click

    @click.command()
    def version():
        print("hello, version")

Main group:

    @click.group()
    def cli():
        pass

    from .version import version
    cli.add_command(version)
