### ISSUE TITLE
How should I test subcommands?

### ISSUE THREAD

**Issue by aspyatkin** [mitsuhiko/click#377]
Hello, I'm having a question about testing `click` applications. E.g. a simple application with subcommands. Some options are global.
```python
@click.group()
@click.option('--startdir', default=None)
@click.pass_context
def cli(ctx, startdir):
    ctx.obj = {'STARTDIR': startdir}

@cli.command()
@cli.pass_context
def sync(ctx):
    click.echo(ctx.obj['STARTDIR'])
```

When I pass `sync` to `CliRunner.invoke`, the whole group will not be executed, so context will not be initialized. When I pass `cli` to `CliRunner.invoke`, I can't specify which subcommand I want to test. The documentation lacks information about that.

**Comment by untitaker** [comment]
You should only pass the `cli` object to the CliRunner and use `CliRunner.invoke(cli, ['sync'])`.

If you find a good place to add this to the docs, PRs are welcome.

**Comment by aspyatkin** [comment]
@untitaker That works, thank you!
