### ISSUE TITLE
SyntaxError on Python 3.2

### ISSUE THREAD

**Issue by sublee** [mitsuhiko/click#382]
On Python 3.2, ``SyntaxError`` occurs from a Unicode literal at ``click/utils.py:301``:

```python
file.write(u'\n')
```

**Comment by untitaker** [comment]
Click does not support Python 3.1 or 3.2. The reason for this is because [PEP 0414](https://www.python.org/dev/peps/pep-0414/) makes support for both Python 2 and 3 much easier.

**Comment by sublee** [comment]
Thanks to answer.
