### ISSUE TITLE
@click.argument with nargs=-1 ignores default

### ISSUE THREAD

**Issue by hugopeixoto** [mitsuhiko/click#390]
Here are two test cases adapted from the existing ones:

```python
def test_eat_options_with_default(runner):
    @click.command()
    @click.argument('files', nargs=-1, default=('test',))
    def cmd(files):
        for filename in files:
            click.echo(filename)

    result = runner.invoke(cmd, ['--'])
    assert result.output == 'test\n'

def test_eat_options_with_default_and_type(runner):
    @click.command()
    @click.argument('files', nargs=-1, default=('test',),type=str)
    def cmd(files):
        for filename in files:
            click.echo(filename)

    result = runner.invoke(cmd, ['--'])
    assert result.output == 'test\n'
```

They both fail, with the output being empty (default is ignored).
I managed to track this down to `click/core.full_process_value`:

```python
def full_process_value(self, ctx, value):
    value = self.process_value(ctx, value)

    if value is None:
        value = self.get_default(ctx)

    if self.required and self.value_is_missing(value):
        raise MissingParameter(ctx=ctx, param=self)

    return value
```

Instead of checking `if value is None`, shouldn't it check for `if self.value_is_missing(value)` ?
With this change, the second test passes, but the first one fails with a type checking exception:

```python
        if self.type.is_composite:
            if self.nargs <= 1:
                raise TypeError('Attempted to invoke composite type '
                                'but nargs has been set to %s.  This is '
                                'not supported; nargs needs to be set to '
                                'a fixed value > 1.' % self.nargs)
```

This can be fixed by adding the following checks to `Parameter.__init__`:

```python
        if nargs < 0 and self.type.is_composite:
            if len(self.type.types) > 0:
                self.type = self.type.types[0]
            else:
                self.type = types.STRING
```

This last part is not very pretty, but with it both tests pass.

**Comment by mitsuhiko** [comment]
I think the actual fix would be to not permit a default value for `nargs -1`.  This in my book seems like the wrong way to do it.  But I need to think about this more.

**Comment by hugopeixoto** [comment]
My use case is building a tool which accepts a list of file names, defaulting to some specific file name. In [my case it was `requirements.txt`](https://github.com/nvie/pip-tools/issues/183), but I suppose the most common case would be stdin (as `"-"`).

I agree that the whole `self.type` shenanigans is a bit odd, I just didn't want to submit an issue without a solution. Maybe those checks could be elegantly integrated into `Parameter.type_cast_value`, or one could add `nargs` to `click/types.convert_type`.

It would be nice to at least change `if value is None` to `self.value_is_missing(value)` in `click/core.full_process_value`. This would allow us to use `nargs=-1` with defaults by specifying the type manually.

**Comment by mitsuhiko** [comment]
This is no longer allowed in click 6.
