### ISSUE TITLE
Remove the "is a work in progress" notice in the README

### ISSUE THREAD

**Issue by pradyunsg** [mitsuhiko/click#394]
The README currently contains:

> This library is a work in progress.  Please give feedback!

I think that this is an incorrect statement. While any non-dead project will always be a work in progress, such a statement suggests the library is immature, which Click (entering 5.x) is most certainly not.

Just my 2 cents... :smiley:

PS: Any plans on moving over to a README.md?

**Comment by untitaker** [comment]
I feel like Click is *not yet* ready to go out of beta, regardless of what the version numbers imply.

I'll accept a PR that removes this though.

**Comment by pradyunsg** [comment]
Yay! :tada:
