### ISSUE TITLE
How do you test a click application from OUTSIDE the application

### ISSUE THREAD

**Issue by sean-abbott** [mitsuhiko/click#400]
I want to be able to use py.test to be able to test click.  Is there any facility built into click to do this?

(i.e., I have a directory structure that looks like
package
- setup.py
- package
    - package.py
- tests
    - test_package.py

I've tried importing package and CliRunner in test_package, but that very much doesn't work.  So. ...not sure what the normal is for this?

**Comment by pombredanne** [comment]
@sean-abbott if click in your path, typically installed in your current virtualenv, things work nicely and out of the box. Your environment is likely not correctly configured.

Did you follow check the  doc?
http://click.pocoo.org/4/quickstart/ and http://click.pocoo.org/4/testing/

**Comment by sean-abbott** [comment]
Yes, I looked at both of those, but they only detail using CliRunner inline.

pip freeze:

click==4.1
click-plugins==1.0
edrbuild==0.1
funcsigs==0.4
mock==1.3.0
pbr==1.4.0
py==1.4.30
pytest==2.7.2
six==1.9.0

directory structure:

./tests
./tests/test_edrbuild.py
./requirements-test.txt
./edrbuild
./edrbuild/__init__.py
./edrbuild/edrbuild.py
./requirements.txt
./setup.py
./DESCRIPTION.rst
./README.md

contents of test_edrbuild:

import click

from click.testing import CliRunner
import unittest
import pytest
from mock import patch


import edrbuild

class TestBuild(unittest.TestCase):

    def test_build_raises_error_missing_dir(tmpdir):

        with pytest.raises(click.UsageError):
          result = edrbuild.runner.invoke(build, ['edr'])

Gives me an error:  AttributeError: 'module' object has no attribute 'runner'.  Inside the module itself, I have a line at the module level:
runner = CliRunner() (with a from click.testing import CliRunner)

I originally had it as tests/test_edrbuild.py being the one ding the CliRunner import, but there doesn't seem to be a way to pass context into CliRunner, which is what seems ideal for this..

**Comment by untitaker** [comment]
Please don't use the bugtracker for support requests. Rather try the IRC channel or stackoverflow.

**Comment by sean-abbott** [comment]
What is the irc channel?  I may be blind, but it doesn't appear to be referenced anywhere?

**Comment by untitaker** [comment]
Sorry, it's ``#pocoo`` on freenode. But I think ``#python`` might help you as well (since your question is not directly related to Click).
