### ISSUE TITLE
Support tagged arguments

### ISSUE THREAD

**Issue by pjz** [mitsuhiko/click#404]
A tagged argument usually has a leading symbol of some sort to help designate its type.  For instance, MH (a commandline email reader) uses a leading `+` to denote folders.  so 

    refile +foo 1

means 'refile message 1 to the folder +foo'.  Note that it's order-independent so is equivalent to

    refile 1 +foo

Similarly many of the `todo.sh` programs use a leading `@` to denote the contexts where it's appropriate to poke the user about the todo.

I'd love to be able to define a ParamType for each of these, but I'm not sure how or if that would work.  My use-case is similar to the MH example I gave above.  So far I've been just gathering all the args as strings and scanning for one that starts with a + and converting the rest to integers... not exactly ideal.

**Comment by untitaker** [comment]
This is a highly specific syntax... I think this should be implemented in the app itself, or a third party package.

On 9 August 2015 00:14:42 CEST, Paul Jimenez <notifications@github.com> wrote:
>A tagged argument usually has a leading symbol of some sort to help
>designate its type.  For instance, MH (a commandline email reader) uses
>a leading `+` to denote folders.  so 
>
>    refile +foo 1
>
>means 'refile message 1 to the folder +foo'.  Note that it's
>order-independent so is equivalent to
>
>    refile 1 +foo
>
>Similarly many of the `todo.sh` programs use a leading `@` to denote
>the contexts where it's appropriate to poke the user about the todo.
>
>I'd love to be able to define a ParamType for each of these, but I'm
>not sure how or if that would work.  My use-case is similar to the MH
>example I gave above.  So far I've been just gathering all the args as
>strings and scanning for one that starts with a + and converting the
>rest to integers... not exactly ideal. 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/404

-- 
Sent from my phone. Please excuse my brevity.

**Comment by mitsuhiko** [comment]
This is already supported anyways:

```python
@click.command()
@click.option('+foo', 'foo', flag_value='+')
@click.option('-foo', 'foo', flag_value='-')
def cli(foo):
    click.echo('Foo: %s' % foo)
```

**Comment by mitsuhiko** [comment]
Ah. Maybe I misunderstood the problem. However a custom type solves that as well.

**Comment by pjz** [comment]
That's an option, not an arg. The list of 'foo' values isn't enumerated (they're folders); I think I'll end up doing it by scanning the arguments and maybe doing validation with a custom type.

**Comment by untitaker** [comment]
By common definition, arguments are not order independent, while options are. Unless your CLI must have that exact syntax for backwards compat purposes, I'd suggest to rethink the interface.

On 11 August 2015 14:46:06 CEST, Paul Jimenez <notifications@github.com> wrote:
>That's an option, not an arg. The list of 'foo' values isn't enumerated
>(they're folders); I think I'll end up doing it by scanning the
>arguments and maybe doing validation with a custom type.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/404#issuecomment-129859595

-- 
Sent from my phone. Please excuse my brevity.

**Comment by pjz** [comment]
So what's the general solution for cases where the list of options isn't known beforehand?  like maybe I have a list of mail folders that I want to make be option flags?  I guess I can load up the list of folders and add them all to the options before parsing the cmdline... no, wait, that won't work for new folders.  Current syntax says if you do something like

    refile 1 3 5-7 +newfolder

then if `newfolder` doesn't exist, it should be created (either automatically or with a y/n prompt, depending on your settings).  It's like some kind of regex-matching flag option: order independent, there can be multiple, they never take a value (because they *are* the value).

**Comment by untitaker** [comment]
What's wrong with:

    refile --folder=./newfolder 1 3 5-7

**Comment by pjz** [comment]
Backwards compatibility with http://www.nongnu.org/nmh/ .  Also: multiple can be specified.

**Comment by untitaker** [comment]
You can use multiple options: http://click.pocoo.org/4/options/#multiple-options

But if you're trying to be backwards compatible, I agree that parsing the arguments yourself is the best solution.
