### ISSUE TITLE
Ignore and pass attributes onto sub application

### ISSUE THREAD

**Issue by foxx** [mitsuhiko/click#413]
In my case, I want to be able to invoke `nose` from a sub command.

For example;

```py
@click.command('test')
def cmd_test():
    """Run tests"""
    import nose
    nose.main()
```

This could then be accessed by doing

```bash
$ python manage.py test [nose options here]
```

This works fine without options, however once you start adding options it breaks;

```bash
$ python manage.py test -w some.app.here
Error: no such option: -w

$ python manage.py test -- -w someapp.here
Error: Got unexpected extra arguments (-w someapp.here)
```

I could add a decorator which checks if `sys.argv` starts with `test` and bypass click from there, but I wanted to see if there was a better way. Is there any way to make `click` bypass all validation checks, allowing a sub application to handle them accordingly? Having to add `--` is a bit of a pain.

Let me know if I haven't explained this very well, thanks!

**Comment by beselim** [comment]
I believe the following might be of help:

```python
LENIENT_CONTEXT = dict(ignore_unknown_options=True, allow_extra_args=True)
@click.command('test', context_settings=LENIENT_CONTEXT)
@click.pass_context
def cmd_test(ctx):
    import nose
    click.echo(ctx.args)
    # Pass ctx.args to nose.main()?
```

**Comment by foxx** [comment]
Thanks for the quick reply, I'll give this a shot, closing for now
