### ISSUE TITLE
handle indented blank lines in wrap_text

### ISSUE THREAD

**Issue by flying-sheep** [mitsuhiko/click#417]
If given a string containing indented blank lines (such as `\t\n`), this function treats everything as single paragraph.

Also I generally don’t get how it’s supposed to handle docstrings. I’d expect it to convert a docstring like this:

```py
def foo():
    """Foo
    
    dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd ftd
    
    \b
    Examples:
      xyz
      abc
    """
    pass
```

into this:

```
Foo

dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd
ftd

Examples:
  xyz
  abc
```

instead i get

```
Foo
    
    dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd
ftd
    
    \x08
    Examples:
      xyz
      abc
```

and when removing the indentation of the blank lines:

```
Foo

    dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd ftd
\x08
    Examples:
      xyz
      abc
```

both is pretty broken IMHO

**Comment by flying-sheep** [comment]
ah, click lets `inspect.getdoc` handle that. nevermind :)

**Comment by untitaker** [comment]
I suspect that Click differentiates between \t and 0x20 whitespace. Not sure if that's a good idea, but apart from that you should follow PEP8 and not use tabs for indentation.

On 28 August 2015 14:50:06 CEST, "Philipp A." <notifications@github.com> wrote:
>If given a string containing indented blank lines (such as `\t\n`),
>this function treats everything as single paragraph.
>
>Also I generally don’t get how it’s supposed to handle docstrings. I’d
>expect it to convert a docstring like this:
>
>```py
>def foo():
>    """Foo
>    
>    dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd ftd
>    
>    \b
>    Examples:
>      xyz
>      abc
>    """
>    pass
>```
>
>into this:
>
>```
>Foo
>
>dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd
>ftd
>
>Examples:
>  xyz
>  abc
>```
>
>instead i get
>
>```
>Foo
>    
>    dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd
>ftd
>    
>    \x08
>    Examples:
>      xyz
>      abc
>```
>
>and when removing the indentation of the blank lines:
>
>```
>Foo
>
>    dusdusdsuiduis dhsui dsui fdsui nsaesdzufsdtuz gdzg sduzfgsuzd ftd
>\x08
>    Examples:
>      xyz
>      abc
>```
>
>both is pretty broken IMHO
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/417

-- 
Sent from my phone. Please excuse my brevity.

**Comment by flying-sheep** [comment]
> I suspect that Click differentiates between \t and 0x20 whitespace.

no, `wrap_text` expands tabs before doing sth. else

> you should follow PEP8 and not use tabs for indentation

no thanks. 1. PEP 8 is a style guide for the stdlib, 2. i can choose whatever style for my own projects, and 3., tabs are more semantic: 1 tab = 1 indentation level.

**Comment by untitaker** [comment]
Afaict this is a bug, possibly caused by the feature to disable paragraph rewrapping (see "Preventing Rewrapping" in the docs). Patches welcome, though I currently don't have a PC to review them.

On 29 August 2015 00:09:00 CEST, "Philipp A." <notifications@github.com> wrote:
>> I suspect that Click differentiates between \t and 0x20 whitespace.
>
>no, `wrap_text` expands tabs before doing sth. else
>
>> you should follow PEP8 and not use tabs for indentation
>
>no thanks. 1. PEP 8 is a style guide for the stdlib, 2. i can choose
>whatever style for my own projects, and 3., tabs are more semantic: 1
>tab = 1 indentation level.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/click/issues/417#issuecomment-135899203

-- 
Sent from my phone. Please excuse my brevity.
