### ISSUE TITLE
click.File type doesn't support universal newline customization

### ISSUE THREAD

**Issue by tsroten** [mitsuhiko/click#426]
`click.File` is a super convenient way to deal with files in Click. Thanks!

In Python, the recommended way to open CSV files is with `newline=''`. Otherwise newlines in CSV files might be interpreted incorrectly. Check out [the first (and only) footnote](https://docs.python.org/3.5/library/functions.html#open) on the CSV module documentation. And, [the documentation on the `open()` function](https://docs.python.org/3.5/library/functions.html#open).

Think it would be doable to add a `newline` keyword argument to the `click.File` type?

The tricky part would be dealing with Python 2/3. `newline` keyword parameters are supported in 2.6/2.7, but not on the built-in `open()` function or `os.fdopen()`. `io.open()` and `io.TextIOWrapper` support it though. So, a potential problem with implementing this is that [non-atomic writes](https://github.com/mitsuhiko/click/blob/master/click/_compat.py#L440) and [atomic writes](https://github.com/mitsuhiko/click/blob/master/click/_compat.py#L469) would have to have some extra logic to account for the newline parameter if it was to be supported in 2.6/2.7 as well.

**Comment by tsroten** [comment]
I'd be happy to submit a pull request if this was something that would be seriously considered.

**Comment by tsroten** [comment]
By the way, here is a test that illustrates the problem.
```python
def test_file_csv(runner):
    @click.command()
    @click.argument('input', type=click.File('r'))
    def readcsv(input):
        rows = tuple(csv.reader(input))
        assert rows[0][0] == 'foo\r\nbar'

    with runner.isolated_filesystem():
        data = '"foo\r\nbar","foo","bar"'
        result = runner.invoke(readcsv, ['-'], input=data)
        assert result.exit_code == 0
```

**Comment by mitsuhiko** [comment]
Not really interested in adding this to be honest.  This is just going to blow it up to become even more complex and it affects only a tiny subset of things.  I'm surprised the csv module even cares about that on Python 3.

I'm going to close this as wontfix as there are good workarounds for this issue available.

**Comment by tsroten** [comment]
Ok, makes sense. I think the problem with writing newlines only affects Windows -- OS X and Linux are generally safe with regard to writing newlines. So, it's definitely a subset of users.

**Comment by SoniEx2** [comment]
I need this for proper input sanitization. any chance of simply passing most kwargs unmodified to the underlying open?

**Comment by SoniEx2** [comment]
(what is the workaround, tho?)

**Comment by kratsg** [comment]
@mitsuhiko  - this should get reopened again. Binary streams might be passed through and there needs to be a customizable option for what triggers a newline, no? E.G. `\r\n` or some custom byte -- and since you support `rb` / `wb` mode - this doesn't seem like a bad idea, especially as you're relying on the `io.BufferedReader` class which allows for this customization...

**Comment by davidism** [comment]
I still agree with why this is closed, so I don't plan to reopen it. Click's type system is extensible to facilitate any specific needs a project has.
