### ISSUE TITLE
Support for common options, or option inheritance

### ISSUE THREAD

**Issue by gotgenes** [mitsuhiko/click#432]
Does Click have a way to support common options between different programs/CLIs?

To give more context, our package provides multiple programs: we'll call them `process_input`, `do_design`, `compress_files`. All of these commands are expected to have a `--logfile` option; that is, they should be able to be invoked on the command line like the following
```
process_input --logifle=/path/to/logfile …
do_design --logfile=/path/to/other_logfile …
…
```

In Click, we could simply repeat the same option in every CLI, e.g.,
```
# in process_input.py

@click.option('--logfile', help='Path to log file', …)
def main():
    …
```
```
# in do_design.py

@click.option('--logfile', help='Path to log file', …)
def main():
    …
```
```
# in compress_files.py

@click.option('--logfile', help='Path to log file', …)
def main():
    …
```

The obvious downside here is a DRY principle violation.

From reading the Click documentation, I get the idea that a Click-centric way to not repeat the same option is to turn the individual programs into subcommands (à la Git's CLI) and make the common/global option part of the master command. This would turn the invocation of our programs into the following:
```
my_program --logifle=/path/to/logfile process_input
my_program --logfile=/path/to/other_logfile do_design
…
```
The challenge here is — again, obviously — this changes the CLI of our programs, which incurs a cost to our users.

Does Click provide a route for us to define common options in one location, and use those options across multiple programs' CLIs?

Currently, we use `argparse` to construct our CLIs. We define a parent CLI with common options in a module, and the individual programs' CLIs inherit these common options via [the `parents` parameter](https://docs.python.org/3/library/argparse.html#parents).

**Comment by untitaker** [comment]
log_option = click.option(...)

    @click.command()  # or group
    @log_option
    def foo():
        pass

    @click.command()  # or group
    @log_option
    def bar():
        pass

**Comment by gotgenes** [comment]
@untitaker Thanks for your answer! I appreciate this!
