### ISSUE TITLE
special character encoding with Python 2.7

### ISSUE THREAD

**Issue by nnako** [mitsuhiko/click#442]
**BACKGROUND**

The German language uses 7 basic special characters: ``ä``, ``ö``, ``ü``, ``Ä``, ``Ö``, ``Ü`` and ``ß``. In former days, when it came to the digital world, they often got replaced by ``ae``, ``oe``, ``ue``,... and ``ss``. Today, everything regarding these representations seems to be solvable using charsets and unicode techniques.

So, I wrote a small Python application which reads characters as arguments from the console (here the Windows cmd shell) and leads them into my application where these characters are compared with other characters from a different source:

I call my application with
``python test.py "abcdefg äöü ÄÖÜ ß"``

stopping within the debugger and printing out the characters on the other side of the code
``sys.argv[1]``  gives  ``'abcdefg \xe4\xf6\xfc \xc4\xd6\xdc \xdf'``

This looks like some representation of UTF-8 to me which corresponds to my system settings.

**PROBLEM**

When I use the Python package "click" to receive user text inputs from the console, the representation is different on the other side. My application looks like:

    @click.command()
    @click.option(
        '--argument',
        default='none',
        is_flag=False,
        help='write aome text"'
        )

    def cli(project):
        # check command line option
        print project

I again call this application with
``python test.py "abcdefg äöü ÄÖÜ ß"``

The print command shows
``abcdefg õ÷³ ─Í▄ ▀``

And just putting the ``project`` variable into the pdb line gives
``u'abcdefg \xf5\xf7\xb3 \u2500\xcd\u2584 \u2580'``

I just don't know how to get a valid string which I can then compare to strings from other sources (also present in utf-8). The comparison always fails.

**Does anybody know, what kind of charset is used by the Python click package to represent the user console input?**

**Comment by Siecje** [comment]
I think this might depend on your shell and terminal settings.

If I save this file as ```test.py```

```Python
import click

@click.command()
@click.argument("argument")
def cli(argument):
    click.echo(argument)

if __name__ == '__main__':
    cli()
```

When I run ```python test.py "abcdefg äöü ÄÖÜ ß"```
The result is ```abcdefg äöü ÄÖÜ ß```

**Comment by nnako** [comment]
Thanks for the reply. Indeed, when I enter your suggested code snippet, my output is as stated in my first post. Regarding my shell and terminal settings, any hints where I could check / alter them?

**Comment by mitsuhiko** [comment]
More information about this is required.  Click does unicode just fine on all environments other than windows.  Windows is a special beast and our hands are bound in making it work for all environments there.  The question is why you get utf-8 data there at all as the windows console does not work with utf-8 normally.

**Comment by codewarrior0** [comment]
> Windows is a special beast 

No kidding! The problem here is that Windows uses codepages, and it uses two *different* kinds of codepages for different things. On Python 2, `sys.argv` comes in encoded with the current ANSI codepage. These have codepage numbers above 1000. However, the encoding for `sys.stdout` is not an ANSI codepage, it is an OEM codepage (from the MS-DOS era), usually with a number below 1000.

The garbage characters you see are a result of decoding the ANSI-encoded bytes from `argv` using the OEM codepage.

The culprit is [`click.types.py:113`](https://github.com/mitsuhiko/click/blob/89d3bfda52d151762e732738b828312a240bf89e/click/types.py#L113), which decodes a StringParam first using stdin's encoding. This is wrong whenever the string was passed via `argv` and not `stdin`.

**Comment by nnako** [comment]
As codewarrior0 said:

> The problem here is that Windows uses codepages,
> and it uses two different kinds of codepages for different things

Yes. There seems to be means to determine the encoding of strings coming from the Windows console as well as strings used internally (preferred by Python v2). Using the following snippet to convert incoming strings (from click / argv consoles on Windows), I now get the desired results:

``` python
    import sys
    import locale

    # get console's codepage
    cp_console = sys.stdout.encoding # results in e.g. 'cp850'

    # get preferred codepage
    cp_preferred = locale.getpreferredencoding() # results in e.g. 'cp1252'

    # transform input string
    console_input = console_input.encode(cp_console).decode(cp_preferred)
```

The resulting string ``console_input`` now has the same encoding as other strings read e.g. from files. Whether this conversion works transparently even on other operating systems or with Python v3, I haven't checked yet.

**Any ideas about possible problems here?**

**Comment by mitsuhiko** [comment]
I think the correct thing to do is to special case no argv passed.  In that case we can recover an unicode argv from OS internals.  I might do that.

**Comment by mitsuhiko** [comment]
I just committed some stuff to make this work on Windows better hopefully.

https://github.com/mitsuhiko/click/commit/acc1e170b79ad4be8986dce183ff327922c126db

**Comment by mitsuhiko** [comment]
I still need to test this on Windows, so it's on a branch with a PR (#451) for the moment.

**Comment by mitsuhiko** [comment]
I merged this now.  On 6.0 at least on Python 2.7 this should work now.  I'm not sure yet what to do with Python 3 because things work a bit different there and it might not be the best idea to play too much around with this.

**Comment by codewarrior0** [comment]
What you did looks fine. On Python 3, `sys.argv` is already unicode (and not limited by codepages), so you've essentially brought Python 2 up to Python 3's level by using those WinAPI functions.

If there's something to worry about, it's that `sys.argv` can now contain characters that can't be encoded using stdout's encoding, so you might want to wrap stdout with something that uses some "replace" or "backslashreplace" error handler.

**Comment by mitsuhiko** [comment]
@codewarrior0 the patch i have allows full unicode output on 2.x through click.echo as I'm now writing to the console directly through the unicode API.  Same as with click.prompt.

**Comment by mitsuhiko** [comment]
(I'm not sure if Python 3 supports unicode console by itself, that requires investigation)

**Comment by codewarrior0** [comment]
Great, looks like you're already on top of things.

It does not look like Python 3 cares about Windows consoles at all (grepping the 3.4 source code has zero hits for WriteConsole). `sys.stdout` is a TextIOWrapper wrapping a couple of other objects, ultimately wrapping a libc `FILE *` (and if you dig into libc, *that* is wrapping WriteFile...) to which bytes are written. The TextIOWrapper uses the 'strict' error handler. This means text sent to stdout is encoded with an OEM codepage and passed to the console host as bytes.

Read/WriteFile will write bytes to the console, and the console host will decode them using its codepage setting (an OEM codepage unless the user changes it with `chcp`).  However, Read/WriteConsoleW *does not* do any decoding or encoding, and bypasses the console's codepage setting to send the text to the console host as text.

So by using Read/WriteConsoleW, you're already way ahead of both Python 2 and 3 with regards to Windows consoles. Don't forget to check that stdio is actually connected to a console!
