### ISSUE TITLE
running command from command weird behaviour

### ISSUE THREAD

**Issue by boazin** [mitsuhiko/click#445]
Assume the following code (bit of reduction from the real case, hope it conveys the problem)

The file is manage.py
```
@click.group()
def cli():
    pass

@cli.command()
@click.option('--run2/--no-run2', is_flag=True, default=False)
def testserver(run2):
    //bla bla bla
    if run2:
        subprocess.Popen(['python','manage.py', 'different_command'])

@cli.command()
def different_command():
    print 'Different command'

if __name__ == "__main__":
    cli()
```

The problem is - that `testserver` command and `different_command` is running twice.
(as if something is not getting cleaned so testserver thinks it needs to be run in the second process)

Am I doing something wrong - calling myself with a different command?

**Comment by Siecje** [comment]
You can pass the context into ```testserver``` and then use that to invoke ```different_command```.

Here is how I am doing it

https://github.com/Siecje/htmd/blob/226cc231d52a53d1b9b916de216224872bb6e07f/htmd/cli.py#L122

**Comment by boazin** [comment]
Yeah... The thing is that I WANT it in a different process. For some reason the part that "decides" which command to run isn't changing...

**Comment by vmalloc** [comment]
This doesn't reproduce on my end (just copying and pasting your code to a clean file)

**Comment by boazin** [comment]
OK. Found the problem. Was totally unrelated. Thanks guys!
