### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by OnionNinja** [mitsuhiko/click#458]
Hi there,

there is a minor error in the docs [here](http://click.pocoo.org/5/options/#yes-parameters) with `prompt` instead of `help`.

Instead of 
```python
@click.command()
@click.confirmation_option(help='Are you sure you want to drop the db?')
def dropdb():
    click.echo('Dropped all tables!')
```
It should be 
```python
@click.command()
@click.confirmation_option(prompt='Are you sure you want to drop the db?')
def dropdb():
    click.echo('Dropped all tables!')
```
**Cheers!**

**Comment by mitsuhiko** [comment]
This is already fixed in latest docs. 09583679ab7b235039ca712c9b044ac397c64322
