### ISSUE TITLE
Chain + Nesting

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/click#462]
Currently it's impossible to enable chain on commands + use multi commands to dispatch to children.  This is awfully limiting.

**Comment by mitsuhiko** [comment]
This is implemented now.  This also fixes #415.  I left a comment there about why it is possible now.

**Comment by mitsuhiko** [comment]
The changeset that changes this is 0a2919f34fcbc635d8530b4c5b60bf119b2bcedb.

**Comment by lec00q** [comment]
Is it still an open issue in 6.7? In #503 @mitsuhiko says that "the chain support is badly broken on 6.0". In fact, adding multi command as subcommand to a multi command that is in chain mode is not supported. Any update on this? Any suggestion on how to implement the same behaviour without chaining?
