### ISSUE TITLE
local variable 'line_len' referenced before assignment with PyPI v6.1

### ISSUE THREAD

**Issue by samuelcolvin** [mitsuhiko/click#470]
I'm getting errors running rq's unit tests since the release of click 6.1.

see https://travis-ci.org/nvie/rq/jobs/93515080

Look at [_termui_impl.py line 222](https://github.com/mitsuhiko/click/blob/6fcda3e5fcddd9001b314e83a1e0546bd22c78c2/click/_termui_impl.py#L222) it does indeed look like `line_len` is referenced when it might not be assigned.

**Comment by kdeldycke** [comment]
Confirming the issue. I just uncovered this bug today with `click` 6.1.

**Comment by kdeldycke** [comment]
Regression has been introduced in commit https://github.com/mitsuhiko/click/commit/c4c9eb23243174cd1ffc9fd0162caf31e93b49ee which was addressing #418.

**Comment by kdeldycke** [comment]
Thanks for the fix and the release ! :+1:
