### ISSUE TITLE
BadOptionUsage exception no longer takes option_name argument

### ISSUE THREAD

**Issue by jonafato** [mitsuhiko/click#474]
During [this change](https://github.com/mitsuhiko/click/commit/5f98f570c08a11e607cccfd9c1b787c69a6a67b7#diff-f391f677ae94d58e508e7af268fdb718R168), `BadOptionUsage`'s `__init__` signature was changed to remove the `option_name` parameter. This seems to be an undocumented breaking change that makes the class less useful programmatically (it removes programmatic access to the attribute that's being used incorrectly). If this was an intentional change, it should be documented in the changelog; otherwise, it's a bug and should be fixed. I'm happy to submit a pull request with the correct change. Can a maintainer clarify what the correct behavior should be?

**Comment by mitsuhiko** [comment]
That's probably not ideal. Willing to accept a pull request here.

**Comment by jonafato** [comment]
@mitsuhiko #475 fixes this.
