### ISSUE TITLE
DS_STORE in pypi tarball

### ISSUE THREAD

**Issue by aviau** [mitsuhiko/click#480]
Hello!

I am packaging click and I found .DS_STORE in the tarball. (```artwork/.DS_Store```).

also:
 - ```examples/.DS_Store```
 - ```examples/imagepipe/.DS_Store```

I guess that was uploaded by mistake!

**Comment by nchammas** [comment]
I suppose this can be addressed by adding `.DS_Store` to the `global-exclude` clause proposed in #483.
