### ISSUE TITLE
Confirmation option

### ISSUE THREAD

**Issue by chernals** [mitsuhiko/click#498]
I have the following confirmation option:
@click.confirmation_option(help='Are you sure you want to create a new MD?')

But the prompt is "Do you want to continue? [y/N]:" 

Am I missing something?

**Comment by ncrocfer** [comment]
The `help` parameter is used to display the message when calling `--help`.

To change the prompt, use the `prompt` parameter :
```python
@click.confirmation_option(help='Confirm the action.', prompt='Are you sure you want to create a new MD?')
```

**Comment by chernals** [comment]
Thanks a bunch!

**Comment by tweeter0830** [comment]
FYI, the click docs indicate otherwise

http://click.pocoo.org/5/options/#yes-parameters
