### ISSUE TITLE
Mutually exclusive option groups

### ISSUE THREAD

**Issue by cosminbasca** [mitsuhiko/click#509]
Is it possible to have mutually exclusive option / argument groups ala argparse: add_mutually_exclusive_group? 

better yet, mutually exclusive groups of (mutually exclusive) groups. In essence tree like grouping strategies for option groups?

Thanks

**Comment by cosminbasca** [comment]
I've implemented my own solution to support option groups and mutually exclusive option groups on top of click. If there is interest, let me know and I will try to integrate it into click and submit a pull request.

Cheers,
Cosmin

**Comment by nchammas** [comment]
Dup of #257.

**Comment by pprince** [comment]
@cosminbasca Could you at least link your solution here (and/or at #257, since this issue will likely be closed as a dup) as an example to others?

**Comment by untitaker** [comment]
Duplicate of #257, which is already resolved (rejected) and has all information you need to implement this manually.
