### ISSUE TITLE
Accessing global context in tests

### ISSUE THREAD

**Issue by adampetrovic** [mitsuhiko/click#516]
Hi,

I am trying to test my Click application in a way that allows me to Mock out the global context object that Click provides. I have a Click 'group' which is called before the execution of each of my Click commands, and in this function I set up some connection logic that is passed into the command using `@click.pass_context`. 

My issue is that I can't seem to find a way to Mock this context object in the testing environment so that I can assert certain calls are made on the connection objects without actually making those calls.

I am aware that I can simply import the command function directly and pass my mocked context object in as a function argument, however many of my commands are decorated with arguments that contain validators that I would like to test too (i.e. using the CliRunner). Is there a way for me to mock this context object in a nice way. The only approach I can think of is to patch the pass_context director before I import my CLI module into my testing module.

Example:

```python
@click.group()
@click.option('-c', '--config', default=os.path.expanduser("~/.configfile"),
              help='Path to configuration file')
@click.pass_context
def main(ctx, config):
    ctx.obj = {
        'config': config,
        'connections': {
            'redis': RedisConnection(config) 
        }
   }

@main.command()
@click.pass_context
def command(ctx):
    conn = ctx.obj['connections']
    conn['redis'].do_thing()  # here i'd like to make the RedisConnection a mock during testing
```

**Comment by untitaker** [comment]
Please use StackOverflow for this.

**Comment by M5oul** [comment]
@adampetrovic, did you post something on StackOverflow?
I am not able to found it.
Or, did you manage to bypass this issue.

I am also facing this case.
I would like to test functions by passing a context.
And, there an external project which would like to use the functions of my project without Click.
And the context is necessary to define the endpoint for the HTTP request to be done.

---
In the end, I found a solution.
If that could help someone, [it’s here](https://git.duniter.org/clients/python/silkaj/issues/223).
