### ISSUE TITLE
Populate default value in help text for options automatically

### ISSUE THREAD

**Issue by robinandeer** [mitsuhiko/click#518]
I was surprised that defaults don't show up in the CLI help texts for options.
Perhaps it would be nice if this is added automatically?

**Comment by Nudies** [comment]
Showing defaults can be controlled via the show_default flag.

**Comment by robinandeer** [comment]
Thank you! I've totally missed that - awesome :)

**Comment by bittner** [comment]
Would it maybe make sense to make `show_default=True` by default? In case a `default=` is set, obviously. A few developers are [wondering just about that](https://stackoverflow.com/questions/39359420/type-and-default-input-value-of-a-click-option-in-help-option) on StackOverflow.
