### ISSUE TITLE
Subcommand option

### ISSUE THREAD

**Issue by mbiokyle29** [mitsuhiko/click#528]
Hello,

I posted this on IRC but didn't get a response, so hopefully I can get this cleared up here. I am developing an CLI which interacts with an API. One of the API resources has a small default json representation and a much larger file representation. The resource is a scientific data file so the json version is the summary and the larger is the raw data. The resource is accesed via a subcommand, and I am trying to add a option which does the following:

 + Acts as a flag to enable the downloading of the raw data file
 + Also can optionally take a path to save the new file to

Here are my decorators:
```python
@cli.command('analyses')
@click.pass_context
@click.option("--raw", default="./", metavar="<str:raw>",
              help=OPTION_HELP['raw'], required=False,
              type=click.Path(exists=True))
@click.option("--table", 'table', is_flag=True,
              help=OPTION_HELP['table'])
@click.argument('analyses', nargs=-1, required=False,
                type=ResourceId)
```

So the `--raw` flag is the one I am working on. Currently I get the error:
```
Error: --raw option requires an argument
```
When I invoke it as a flag (i.e. without giving it a value) it does not seem to inherit the default value. When I set `is_flag`
```
TypeError: coercing to Unicode: need string or buffer, bool found
```

One final note, the `analyses` argument is one or more resource uris.
So here is what the actual calls would look like:
```
cli analyses --raw /some/file/path $RESOURCE_ID
cli analyses --raw $RESOURCE_ID
cli analyses $RESOURCE_ID --raw
```
The second one looks a bit funky, but I have logic to handle it (the resource id's have a structure so the value of raw is checked and if it matches the user is prompted). The only one that does not work is the third one. Any help is much appreciated!

click-6.2
python 2.7
Ubuntu 14.04 LTS

**Comment by untitaker** [comment]
There's no way to "optionally" take a value. It either is a flag or it takes a value. Anything else creates parsing ambiguities:

    command --foo bar baz

Is `bar` now a value for `--foo` or an argument?

So the answer is, create a separate option `--raw-path`.

**Comment by untitaker** [comment]
Also please use StackOverflow, you'll get a quicker answer there.
