### ISSUE TITLE
click bashcomplete falls short of one argument, shows wrong options

### ISSUE THREAD

**Issue by untitaker** [mitsuhiko/click#530]
Using the following application: https://gist.github.com/untitaker/b05a2c321b6303974152
and this line to activate bash completion:

    eval "$(_LOL_COMPLETE=source lol)"

We find a few bugs:

* Typing `lol<space>`, and hitting tab N times, it completes to `lol sub sub sub`, where `sub` is repeated N times.
* Typing `lol sub --` and hitting tab will suggest options that are registered on the group, and are invalid in this location.

This patch fixes both problems:

```diff
diff --git a/click/_bashcomplete.py b/click/_bashcomplete.py
index 43feffb..fd62137 100644
--- a/click/_bashcomplete.py
+++ b/click/_bashcomplete.py
@@ -29,6 +29,7 @@ def get_completion_script(prog_name, complete_var):
 
 
 def resolve_ctx(cli, prog_name, args):
+    args = [''] + args
     ctx = cli.make_context(prog_name, args, resilient_parsing=True)
     while ctx.args and isinstance(ctx.command, MultiCommand):
         cmd = ctx.command.get_command(ctx, ctx.args[0])
```

and I have no idea why.

**Comment by katakumpo** [comment]
I can confirm this works nicely :)

**Comment by kuchi** [comment]
Appears this bug has also been documented in  #471.

**Comment by untitaker** [comment]
Closing as duplicate.

**Comment by untitaker** [comment]
6.5 is out.
